/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/shared/Button.vue')['default']
    ConnectionIndicator: typeof import('./../components/ConnectionIndicator.vue')['default']
    Icon: typeof import('./../components/shared/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('reka-ui')['Separator']
    SimpleSeparator: typeof import('./../components/shared/SimpleSeparator.vue')['default']
    Textarea: typeof import('./../components/shared/Textarea.vue')['default']
  }
}
