/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<
      'Home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Coinflip': RouteRecordInfo<
      'Coinflip',
      '/coin-flip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'End': RouteRecordInfo<
      'End',
      '/end',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Play': RouteRecordInfo<
      'Play',
      '/play',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Setup': RouteRecordInfo<
      'Setup',
      '/setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/Home.vue': {
      routes:
        | 'Home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Coinflip.vue': {
      routes:
        | 'Coinflip'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/End.vue': {
      routes:
        | 'End'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Play.vue': {
      routes:
        | 'Play'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Setup.vue': {
      routes:
        | 'Setup'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
